#!/usr/bin/env bash
# Dump `sf sobject describe` for the four objects Vista touches and print the field
# summary the data contract needs. Run from a machine that has `sf` and the org alias.
#
#   bash docs/describe.sh            # uses alias "myorg"
#   bash docs/describe.sh prod       # another alias
#
# Output: docs/describe/<Object>.json (git-ignored) and docs/describe/SUMMARY.md (commit this).
set -euo pipefail
ORG="${1:-myorg}"
cd "$(dirname "$0")"
mkdir -p describe
OUT=describe/SUMMARY.md
command -v sf >/dev/null || { echo "sf CLI not found. npm i -g @salesforce/cli"; exit 1; }
sf org display -o "$ORG" >/dev/null || { echo "org alias '$ORG' not authenticated"; exit 1; }

{
  echo "# Describe summary — org alias \`$ORG\` — $(date -u +%FT%TZ)"
  echo
  echo "Generated by docs/describe.sh. Paste this back to finish docs/data-contract.md."
} > "$OUT"

for OBJ in WorkOrder SA_Expense__c Case Job__c ServiceAppointment AssignedResource ServiceResource WorkOrderLineItem WorkType; do
  echo "== $OBJ"
  sf sobject describe -s "$OBJ" -o "$ORG" --json > "describe/$OBJ.json"
  node - "$OBJ" "describe/$OBJ.json" >> "$OUT" <<'NODE'
const [,, obj, file] = process.argv;
const d = JSON.parse(require('fs').readFileSync(file, 'utf8')).result;
const rows = d.fields.map(f => ({
  name: f.name, type: f.type, len: f.length || '', req: !f.nillable && !f.defaultedOnCreate ? 'yes' : '',
  create: f.createable ? 'c' : '', update: f.updateable ? 'u' : '',
  ref: (f.referenceTo || []).join('/'),
  pick: f.picklistValues && f.picklistValues.length ? f.picklistValues.filter(p => p.active).map(p => p.value).join(' | ') : ''
}));
const long = rows.filter(r => r.type === 'textarea' && Number(r.len) > 255);
console.log(`\n## ${obj}  (${d.label}; ${rows.length} fields; createable=${d.createable} updateable=${d.updateable})\n`);
if (d.recordTypeInfos && d.recordTypeInfos.length > 1) {
  console.log('Record types: ' + d.recordTypeInfos.map(r => `${r.name} (${r.recordTypeId}${r.defaultRecordTypeMapping ? ', default' : ''})`).join(', ') + '\n');
}
console.log(`**Long-text fields (manifest candidates):** ${long.length ? long.map(r => `\`${r.name}\` (${r.len})`).join(', ') : 'none'}\n`);
console.log('| Field | Type | Len | Req | C/U | Ref | Picklist values |');
console.log('|---|---|---|---|---|---|---|');
for (const r of rows) console.log(`| ${r.name} | ${r.type} | ${r.len} | ${r.req} | ${r.create}${r.update} | ${r.ref} | ${r.pick.replace(/\|/g, '\\|')} |`);
NODE
done
echo
echo "Wrote $OUT"
grep -A1 'Long-text fields' "$OUT" | grep -v '^--' || true
