#!/usr/bin/env bash
# Lists existing automation on the objects Vista touches, so the new flow doesn't collide with it.
# Read-only. Safe against production:  ORG=myorg bash salesforce/automation-check.sh
# Output: vista/docs/describe/AUTOMATION.md (commit it).
set -euo pipefail
cd "$(dirname "$0")"
ORG="${ORG:-myorg}"
OUT=../docs/describe/AUTOMATION.md
q() { sf data query -o "$ORG" "$@" --json 2>/dev/null || echo '{"result":{"records":[]}}'; }
TABLES="SA_Expense__c WorkOrder WorkOrderLineItem ServiceAppointment"
{
  echo "# Automation on Vista objects — org \`$ORG\` — $(date -u +%FT%TZ)"
  echo
  echo "Generated by salesforce/automation-check.sh."
  echo
  echo "## Active flows"
  q -q "SELECT ApiName, Label, ProcessType, TriggerType, TriggerObjectOrEventLabel FROM FlowDefinitionView WHERE IsActive = true" | node -e '
    let s="";process.stdin.on("data",d=>s+=d).on("end",()=>{const r=JSON.parse(s).result.records;
    const want=new Set(["SA Expense","Work Order","Work Order Line Item","Service Appointment"]);
    const rows=r.filter(x=>want.has(x.TriggerObjectOrEventLabel));
    console.log("\n| Flow | Object | Trigger | Type |\n|---|---|---|---|");
    rows.forEach(x=>console.log(`| ${x.Label} (\`${x.ApiName}\`) | ${x.TriggerObjectOrEventLabel} | ${x.TriggerType||""} | ${x.ProcessType} |`));
    console.log(`\n${rows.length} record-triggered flows on these objects; ${r.length} active flows in the org.`)})'
  echo
  echo "## Approval processes"
  q -q "SELECT Name, DeveloperName, TableEnumOrId, State, Type FROM ProcessDefinition" | node -e '
    let s="";process.stdin.on("data",d=>s+=d).on("end",()=>{const r=JSON.parse(s).result.records;
    console.log("\n| Name | Object | State | Type |\n|---|---|---|---|");
    r.forEach(x=>console.log(`| ${x.Name} (\`${x.DeveloperName}\`) | ${x.TableEnumOrId} | ${x.State} | ${x.Type} |`));
    console.log(`\n${r.length} approval processes in the org. **If one is on SA Expense, Vista submits through it with the PM as submitter.**`)})'
  echo
  echo "## Apex triggers"
  q --use-tooling-api -q "SELECT Name, TableEnumOrId, Status FROM ApexTrigger WHERE Status = 'Active'" | node -e '
    let s="";process.stdin.on("data",d=>s+=d).on("end",()=>{const want=new Set(process.argv[1].split(" "));const r=JSON.parse(s).result.records.filter(x=>want.has(x.TableEnumOrId));
    console.log("\n| Trigger | Object |\n|---|---|");r.forEach(x=>console.log(`| ${x.Name} | ${x.TableEnumOrId} |`));console.log(`\n${r.length} active triggers on these objects.`)})' "$TABLES"
  echo
  echo "## How SA Expense statuses are used (last 90 days)"
  q -q "SELECT Status__c s, Type__c t, COUNT(Id) n FROM SA_Expense__c WHERE CreatedDate = LAST_N_DAYS:90 GROUP BY Status__c, Type__c" | node -e '
    let s="";process.stdin.on("data",d=>s+=d).on("end",()=>{const r=JSON.parse(s).result.records;
    console.log("\n| Status | Type | Count |\n|---|---|---|");r.forEach(x=>console.log(`| ${x.s} | ${x.t} | ${x.n} |`))})'
  echo
  echo "## How visits link to work orders (last 90 days)"
  q -q "SELECT ParentRecordType p, COUNT(Id) n FROM ServiceAppointment WHERE CreatedDate = LAST_N_DAYS:90 AND Work_Order__c = null GROUP BY ParentRecordType" | node -e '
    let s="";process.stdin.on("data",d=>s+=d).on("end",()=>{const r=JSON.parse(s).result.records;
    console.log("\nVisits with **no** Work_Order__c, by parent type (the flow relies on Work_Order__c):\n\n| Parent type | Count |\n|---|---|");r.forEach(x=>console.log(`| ${x.p} | ${x.n} |`));if(!r.length)console.log("| (none) | 0 |")})'
} > "$OUT"
echo "Wrote $OUT"
