#!/usr/bin/env bash
# Read-only: pulls the existing SA Expense approval process(es) so Vista can submit through them.
# Safe on production:  ORG=myorg bash salesforce/retrieve-approval.sh
# Output: salesforce/reference/approvalProcesses/*.xml (never deployed) and docs/describe/APPROVAL.md (commit both).
set -euo pipefail
cd "$(dirname "$0")"
ORG="${ORG:-myorg}"
command -v sf >/dev/null || { echo "sf CLI not found"; exit 1; }
NAMES=$(sf data query -o "$ORG" -q "SELECT DeveloperName, TableEnumOrId FROM ProcessDefinition" --json | node -e '
  let s="";process.stdin.on("data",d=>s+=d).on("end",()=>{const r=JSON.parse(s).result.records;
  console.log(r.filter(x=>/SA_Expense__c/i.test(x.TableEnumOrId)||/sa.?expense/i.test(x.DeveloperName)).map(x=>x.DeveloperName).join(" "))})')
[ -n "$NAMES" ] || { echo "No approval process found on SA_Expense__c. Check docs/describe/AUTOMATION.md."; exit 1; }
TMP=$(mktemp -d); trap 'rm -rf "$TMP"' EXIT
cp sfdx-project.json "$TMP/"; mkdir -p "$TMP/force-app"
ARGS=(); for n in $NAMES; do ARGS+=(-m "ApprovalProcess:SA_Expense__c.$n"); done
( cd "$TMP" && sf project retrieve start -o "$ORG" "${ARGS[@]}" -m "Workflow:SA_Expense__c" >/dev/null )
mkdir -p reference/approvalProcesses
cp "$TMP"/force-app/main/default/approvalProcesses/*.xml reference/approvalProcesses/
node - reference/approvalProcesses/*.xml > ../docs/describe/APPROVAL.md <<'NODE'
const fs = require('fs');
const pick = (x, tag) => [...x.matchAll(new RegExp(`<${tag}>([\\s\\S]*?)</${tag}>`, 'g'))].map(m => m[1]);
const strip = s => s.replace(/<[^>]+>/g, ' ').replace(/\s+/g, ' ').trim();
console.log(`# SA Expense approval process(es) — ${new Date().toISOString()}\n\nGenerated by salesforce/retrieve-approval.sh. Full XML in salesforce/reference/approvalProcesses/.\n`);
for (const f of process.argv.slice(2)) {
  const x = fs.readFileSync(f, 'utf8');
  console.log(`## ${pick(x, 'label')[0] || f}  (active: ${pick(x, 'active')[0]})\n`);
  console.log(`- **Entry criteria:** ${pick(x, 'entryCriteria').map(strip).join(' ') || '(none)'}`);
  console.log(`- **Allowed submitters:** ${pick(x, 'allowedSubmitters').map(strip).join('; ')}`);
  console.log(`- **Record editability while pending:** ${pick(x, 'recordEditability')[0] || ''}`);
  console.log(`- **Initial submission actions:** ${pick(x, 'initialSubmissionActions').map(strip).join('; ') || '(none)'}`);
  pick(x, 'approvalStep').forEach((s, i) => console.log(`- **Step ${i + 1}:** ${strip(pick(s, 'label')[0] || '')} — approvers: ${pick(s, 'assignedApprover').map(strip).join('; ')} — criteria: ${pick(s, 'entryCriteria').map(strip).join(' ') || 'all'}`));
  console.log(`- **Final approval actions:** ${pick(x, 'finalApprovalActions').map(strip).join('; ') || '(none)'}`);
  console.log(`- **Final rejection actions:** ${pick(x, 'finalRejectionActions').map(strip).join('; ') || '(none)'}\n`);
}
NODE
WF="$TMP/force-app/main/default/workflows/SA_Expense__c.workflow-meta.xml"
if [ -f "$WF" ]; then
  mkdir -p reference/workflows && cp "$WF" reference/workflows/
  node - "$WF" >> ../docs/describe/APPROVAL.md <<'NODE'
const x = require('fs').readFileSync(process.argv[2], 'utf8');
const pick = (s, tag) => [...s.matchAll(new RegExp(`<${tag}>([\\s\\S]*?)</${tag}>`, 'g'))].map(m => m[1]);
console.log('## Field updates used by the approval processes\n\n| Name | Field | Sets to |\n|---|---|---|');
for (const fu of pick(x, 'fieldUpdates')) {
  const v = pick(fu, 'formula')[0] || pick(fu, 'literalValue')[0] || pick(fu, 'lookupValue')[0] || pick(fu, 'operation')[0] || '';
  console.log(`| ${pick(fu, 'fullName')[0]} | ${pick(fu, 'field')[0]} | ${v.replace(/\|/g, '\\|').replace(/&quot;/g, '"').replace(/&amp;/g, '&')} |`);
}
NODE
fi
echo "Wrote docs/describe/APPROVAL.md and salesforce/reference/"
